name: Build and test

on:
  push:
    branches: [ python-backend ]
  pull_request:
    branches: [ python-backend ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Build
        run: JDK_9="$JAVA_HOME" ./gradlew dist
      - name: Run box tests (succeed even if they fail)
        run: JDK_9="$JAVA_HOME" ./gradlew :python:box.tests:pythonTest --tests "org.jetbrains.kotlin.python.test.ir.semantics.IrPythonCodegenBoxTestGenerated" || true
